# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './NotesP5.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_P5(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 229)
        self.submitButtonP5 = QtWidgets.QToolButton(Form)
        self.submitButtonP5.setGeometry(QtCore.QRect(185, 180, 20, 20))
        self.submitButtonP5.setText("")
        self.submitButtonP5.setObjectName("submitButtonP5")
        self.noteBoxP5 = QtWidgets.QPlainTextEdit(Form)
        self.noteBoxP5.setGeometry(QtCore.QRect(50, 40, 251, 121))
        self.noteBoxP5.setObjectName("noteBoxP5")
        self.cancelButtonP5 = QtWidgets.QToolButton(Form)
        self.cancelButtonP5.setGeometry(QtCore.QRect(145, 180, 20, 20))
        self.cancelButtonP5.setText("")
        self.cancelButtonP5.setObjectName("cancelButtonP5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 10, 91, 21))
        self.label.setObjectName("label")
        self.hiddenVariableP5 = QtWidgets.QLabel(Form)
        self.hiddenVariableP5.setGeometry(QtCore.QRect(10, 200, 20, 20))
        self.hiddenVariableP5.setText("")
        self.hiddenVariableP5.setObjectName("hiddenVariableP5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cougar-Log"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">Log Notes</p></body></html>"))
