# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './TutorInformationP2-0v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_P2_0(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(356, 269)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 75, 127, 21))
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(45, 75, 65, 21))
        self.label_3.setObjectName("label_3")
        self.form_title = QtWidgets.QLabel(Form)
        self.form_title.setGeometry(QtCore.QRect(128, 10, 111, 16))
        self.form_title.setObjectName("form_title")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 110, 127, 21))
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 70, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(120, 40, 127, 21))
        self.lineEdit_1.setInputMask("")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(21, 110, 88, 21))
        self.label_4.setObjectName("label_4")
        self.alert_info_error = QtWidgets.QLabel(Form)
        self.alert_info_error.setGeometry(QtCore.QRect(68, 225, 231, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.alert_info_error.setFont(font)
        self.alert_info_error.setObjectName("alert_info_error")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 145, 127, 21))
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(39, 145, 70, 21))
        self.label_5.setObjectName("label_5")
        self.cancelButtonP1 = QtWidgets.QToolButton(Form)
        self.cancelButtonP1.setGeometry(QtCore.QRect(154, 195, 20, 20))
        self.cancelButtonP1.setText("")
        self.cancelButtonP1.setObjectName("cancelButtonP1")
        self.submitButtonP1 = QtWidgets.QToolButton(Form)
        self.submitButtonP1.setGeometry(QtCore.QRect(194, 195, 20, 20))
        self.submitButtonP1.setText("")
        self.submitButtonP1.setObjectName("submitButtonP1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_1, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.lineEdit_3)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cougar-Log"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Last Name:</span></p></body></html>"))
        self.form_title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">Tutor Information</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p>First Name:</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Discord Handle:</span></p></body></html>"))
        self.alert_info_error.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Discord Tag:</span></p></body></html>"))
