# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './WidgetP2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_P2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(410, 357)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(140, 10, 251, 241))
        self.listWidget.setObjectName("listWidget")
        self.tutorFirstName = QtWidgets.QLabel(Form)
        self.tutorFirstName.setGeometry(QtCore.QRect(40, 80, 61, 21))
        self.tutorFirstName.setObjectName("tutorFirstName")
        self.tutorLastName = QtWidgets.QLabel(Form)
        self.tutorLastName.setGeometry(QtCore.QRect(40, 120, 61, 21))
        self.tutorLastName.setObjectName("tutorLastName")
        self.tutormyUHID = QtWidgets.QLabel(Form)
        self.tutormyUHID.setGeometry(QtCore.QRect(40, 40, 61, 21))
        self.tutormyUHID.setObjectName("tutormyUHID")
        self.tutorDiscordHandle = QtWidgets.QLabel(Form)
        self.tutorDiscordHandle.setGeometry(QtCore.QRect(20, 160, 101, 21))
        self.tutorDiscordHandle.setObjectName("tutorDiscordHandle")
        self.tutorDiscordTag = QtWidgets.QLabel(Form)
        self.tutorDiscordTag.setGeometry(QtCore.QRect(50, 200, 41, 21))
        self.tutorDiscordTag.setObjectName("tutorDiscordTag")
        self.tutorDiscordHashTag = QtWidgets.QLabel(Form)
        self.tutorDiscordHashTag.setGeometry(QtCore.QRect(40, 200, 16, 21))
        self.tutorDiscordHashTag.setObjectName("tutorDiscordHashTag")
        self.alert_file_exists = QtWidgets.QLabel(Form)
        self.alert_file_exists.setGeometry(QtCore.QRect(140, 270, 251, 20))
        self.alert_file_exists.setText("")
        self.alert_file_exists.setObjectName("alert_file_exists")
        self.exportButton = QtWidgets.QToolButton(Form)
        self.exportButton.setGeometry(QtCore.QRect(295, 300, 20, 20))
        self.exportButton.setText("")
        self.exportButton.setObjectName("exportButton")
        self.addStudentButton = QtWidgets.QToolButton(Form)
        self.addStudentButton.setGeometry(QtCore.QRect(255, 300, 20, 20))
        self.addStudentButton.setText("")
        self.addStudentButton.setObjectName("addStudentButton")
        self.editTutorButton = QtWidgets.QToolButton(Form)
        self.editTutorButton.setGeometry(QtCore.QRect(215, 300, 20, 20))
        self.editTutorButton.setText("")
        self.editTutorButton.setObjectName("editTutorButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cougar-Log"))
        self.tutorFirstName.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tutorLastName.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tutormyUHID.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tutorDiscordHandle.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tutorDiscordTag.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tutorDiscordHashTag.setText(_translate("Form", "<html><head/><body><p>#</p></body></html>"))

